spring:
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/museum_db}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:password}

  flyway:
    enabled: true
    baseline-on-migrate: true

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
